version: 0.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
test_script:
- cmd: tests.bat
artifacts:
- path: '**\*.nupkg'
  name: Packages
build:
  publish_nuget: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: KHXvcB9JDeK7JCAJrCzJSuf0U32VdwTaBnAnabdfoBH4PWT64N7I+inB4bZsOHhj