version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
  - cmd: nuget restore
  - cmd: dotnet restore
  - ps: (Get-Content .\ModelGenerator\ModelGenerator.csproj).replace('<Version>0.0.0</Version>', '<Version>' + $Env:APPVEYOR_BUILD_VERSION + '</Version>') | Set-Content .\ModelGenerator\ModelGenerator.csproj
  - ps: (Get-Content .\ModelGenerator\ModelGenerator.csproj).replace('<FileVersion>0.0.0</FileVersion>', '<FileVersion>' + $Env:APPVEYOR_BUILD_VERSION + '</FileVersion>') | Set-Content .\ModelGenerator\ModelGenerator.csproj
  - ps: (Get-Content .\ModelGenerator\ModelGenerator.csproj).replace('<InformationalVersion>0.0.0</InformationalVersion>', '<InformationalVersion>' + $Env:APPVEYOR_BUILD_VERSION + '</InformationalVersion>') | Set-Content .\ModelGenerator\ModelGenerator.csproj
skip_tags: true
build:
  verbosity: minimal
  project: ModelGenerator.sln
after_build:
  - cmd: nuget pack .\ModelGenerator\ModelGenerator.nuspec -version %APPVEYOR_BUILD_VERSION%
before_test:
  - cmd: mkdir %APPVEYOR_BUILD_FOLDER%\reports\coverage
  - cmd: nuget install OpenCover -ExcludeVersion -OutputDirectory tools
  - cmd: nuget install xunit.runner.console -ExcludeVersion -OutputDirectory tools
  - cmd: nuget install coveralls.io -ExcludeVersion -OutputDirectory tools
test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && set APPVEYOR_API_URL= && tools\OpenCover\tools\OpenCover.Console.exe -target:"tools\xunit.runner.console\tools\xunit.console.x86.exe" -targetargs:"ModelGenerator.Tests\bin\Release\net46\ModelGenerator.Tests.dll -noShadow -xml test-results.xml" -register:user -output:"reports\coverage\coverage.xml" -skipautoprops -filter:"+[ModelGenerator]*"  -excludebyattribute:*.ExcludeFromCodeCoverage* -mergebyhash -returntargetcode
after_test:
  - ps: .\upload-results.ps1
  - cmd: tools\coveralls.io\tools\coveralls.net.exe reports\coverage\coverage.xml
environment:
  COVERALLS_REPO_TOKEN:
    secure: KHXvcB9JDeK7JCAJrCzJSuf0U32VdwTaBnAnabdfoBH4PWT64N7I+inB4bZsOHhj
deploy:
- provider: GitHub
  artifact: ModelGenerator           
  draft: false
  prerelease: true
  on:
    branch: master
  auth_token:
    secure: mlxIUvXrZV1LAtYt9DXC7hWFCE7oHl3QEFxkKTTrpCYKjyNTeWFpZhrna9zZjEZe
- provider: NuGet
  server: https://www.myget.org/F/trichards57/api/v2/package
  api_key:
    secure: WwUh/s6u+Z0zdCdYBKhYyozI5WbWo0ZmBqAsRcpIwwahVUzZSFuwCI2yJbOY7CTJ
  symbol_server: https://www.myget.org/F/trichards57/symbols/api/v2/package
  skip_symbols: false
  artifact: ModelGenerator
artifacts:
  - path: '*.nupkg'
    name: ModelGenerator