version: 0.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
skip_tags: true
build:
  verbosity: minimal
  publish_nuget: true
  project: ModelGenerator.sln
test_script:
- cmd: tests.bat
environment:
  COVERALLS_REPO_TOKEN:
    secure: KHXvcB9JDeK7JCAJrCzJSuf0U32VdwTaBnAnabdfoBH4PWT64N7I+inB4bZsOHhj
deploy:
- provider: GitHub
  artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    branch: master
  auth_token:
    secure: mlxIUvXrZV1LAtYt9DXC7hWFCE7oHl3QEFxkKTTrpCYKjyNTeWFpZhrna9zZjEZe
- provider: NuGet
  server: https://www.myget.org/F/trichards57/api/v2/package
  api_key:
    secure: WwUh/s6u+Z0zdCdYBKhYyozI5WbWo0ZmBqAsRcpIwwahVUzZSFuwCI2yJbOY7CTJ
  symbol_server: https://www.myget.org/F/trichards57/symbols/api/v2/package
  skip_symbols: false