version: 0.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
  publish_nuget: true
test_script:
- cmd: tests.bat
artifacts:
- path: '**\*.nupkg'
  name: Packages
environment:
  COVERALLS_REPO_TOKEN:
    secure: KHXvcB9JDeK7JCAJrCzJSuf0U32VdwTaBnAnabdfoBH4PWT64N7I+inB4bZsOHhj